### PR TITLE
Add 1.19.1 Support

### PR DESCRIPTION
**Pull request by james090500**

### CODE REVIEW

**Comment by CamperSamu** [comment]
Sorry if I'm bothering you, but can you put a release on your repo for now?
I need this plugin quick and right now I can't build it myself since I'm not at home with a stable (and most importantly unlimited) connection to download everything

**Comment by james090500** [comment]
> Sorry if I'm bothering you, but can you put a release on your repo for now? I need this plugin quick and right now I can't build it myself since I'm not at home with a stable (and most importantly unlimited) connection to download everything

https://github.com/CapeCraft/VelocityPacketInjector/releases/tag/1.1.2

**Comment by CamperSamu** [comment]
Thanks a lot!

**Comment by Lui798** [comment]
Going to archive this project as I have no interest maintaining this as I no longer use TAB on the proxy. Sorry guys! You can try looking into running TAB on your backend with a MySQL server if its feasible for you.

**Pull request closed without merging**
